issue-125 : replaced uuids with updated values
openBackhaul/RegistryOffice pull request #152
Opened 2022-10-10 11:33 UTC by MartinSunal

see https://github.com/openBackhaul/ApplicationPattern/blob/develop/doc/ElementsApplicationPattern/Names/StructureOfUuids/StructureOfUuids.md
Fixes https://github.com/openBackhaul/RegistryOffice/issues/125

Signed-off-by: Martin Sunal [martin.sunal@paxet.io](mailto:martin.sunal@paxet.io)

2022-10-10 17:43 UTC, PrathibaJee requested changes

2022-10-10 17:43 UTC, PrathibaJee commented on RegistryOffice.yaml
> +                    update or create [/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-op-c-is-*-1-0-0-002/layer-protocol=0/operation-client-interface-1-0:operation-client-interfa
In /v1/notify-deregistrations, subscriber-operation is referring ro-2-0-0-op-c-is-*-1-0-0-002.
Which is not referring the uuid of “/v1/disregard-application”.
**Proposal :** 
The sequence number needs to be “004” and the APISegment should be “im” , ro-2-0-0-op-c-im-*-1-0-0-004.

2022-10-10 17:43 UTC, PrathibaJee commented on RegistryOffice.yaml
> +                    update or create [/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-op-c-*-*-1-0-0-??2/layer-protocol=0/operation-client-interface-1-0:operation-client-interfac
In /v1/notify-withdrawn-approvals , subscriber-operation is referring ro-2-0-0-op-c-*-*-1-0-0-??2.
Which is not referring the uuid of “/v1/disregard-application”.
**Proposal :** 
The sequence number needs to be “004” , ro-2-0-0-op-c-im-*-1-0-0-004.

2022-10-10 17:43 UTC, PrathibaJee commented on RegistryOffice.yaml
> +                            from [/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-op-c-*-*-1-0-0-??2/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-pa
In /v1/notify-withdrawn-approvals , subscriber-operation is referring ro-2-0-0-op-c-*-*-1-0-0-??2.
Which is not referring the uuid of “/v1/disregard-application”.
**Proposal :** 
The sequence number needs to be “004” , ro-2-0-0-op-c-im-*-1-0-0-004.

2022-10-10 17:43 UTC, PrathibaJee commented on RegistryOffice.yaml
> +                    update or create [/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-op-c-*-*-1-0-0-001/layer-protocol=0/operation-client-interface-1-0:operation-client-interfac
In /v1/notify-approvals, subscriber-operation is referring ro-2-0-0-op-c-*-*-1-0-0-001.
Which is not referring the uuid of “/v1/regard-application”.
**Proposal :** 
The sequence number needs to be “003” , ro-2-0-0-op-c-im-*-1-0-0-003.

2022-10-10 17:43 UTC, PrathibaJee commented on RegistryOffice.yaml
> +                    update or create [/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-op-c-bs-*/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-pac/ope
In /v1/register-application, embedding-operation attribute is referring to ro-2-0-0-op-c-bs-*.
Which is not referring the uuid of “/v1/embed-yourself”.
**Proposal :** 
The sequence number needs to be “000”, also the APISegment should be “im” , ro-2-0-0-op-c-im-*-1-0-0-000.

2022-10-10 17:43 UTC, PrathibaJee commented on RegistryOffice.yaml
> +                    update or create [/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-op-c-bs-*/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-pac/ope
In /v1/register-application, client-update-operation attribute is referring to ro-2-0-0-op-c-bs-*.
Which is not referring the uuid of “/v1/update-client”.
**Proposal :** 
The sequence number needs to be “001”, also the APISegment should be “im” , ro-2-0-0-op-c-im-*-1-0-0-001.

2022-10-10 17:43 UTC, PrathibaJee commented on RegistryOffice.yaml
> +                            from [/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-op-c-is-*-1-0-0-??2/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-p
In /v1/notify-deregistrations, subscriber-operation is referring ro-2-0-0-op-c-is-*-1-0-0-??2.
Which is not referring the uuid of “/v1/disregard-application”.
**Proposal :** 
The sequence number needs to be “004” and the APISegment should be “im” , ro-2-0-0-op-c-im-*-1-0-0-004.

2022-10-10 17:43 UTC, PrathibaJee commented on RegistryOffice.yaml
> +                            from [/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-op-c-*-*-1-0-0-??1/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-pa
In /v1/notify-approvals, subscriber-operation is referring ro-2-0-0-op-c-*-*-1-0-0-??1.
Which is not referring the uuid of “/v1/regard-application”.
**Proposal :** 
The sequence number needs to be “003” , ro-2-0-0-op-c-im-*-1-0-0-003.

2022-10-10 17:43 UTC, PrathibaJee commented on RegistryOffice.yaml
> +                            from [/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-op-c-*/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-pac/operation-
In /v1/register-application, embedding-operation attribute is referring to ro-2-0-0-op-c-* , which is not referring the uuid of “/v1/embed-yourself”.
**Proposal :** 
The sequence number needs to be “000”, also the APISegment should be “im” , ro-2-0-0-op-c-im-*-1-0-0-000.

2022-10-10 17:43 UTC, PrathibaJee commented on RegistryOffice.yaml
> +                            from [/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-op-c-*/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-pac/operation-
In /v1/register-application, client-update-operation attribute is referring to ro-2-0-0-op-c-* , which is not referring the uuid of “/v1/update-client”.
**Proposal :** 
The sequence number needs to be “001”, also the APISegment should be “im” , ro-2-0-0-op-c-im-*-1-0-0-001.

2022-10-11 12:44 UTC, IswaryaaS commented on RegistryOffice+services.yaml
> +      uuid: ro-2-0-0-http-c-bm-ro-2-0-0-000
In UUID of RO client, the client release-number would be "1.0.0". 
For example, ro-2-0-0-http-c-bm-ro-**2-0-0**-000 should be ro-2-0-0-http-c-bm-ro-**1-0-0**-000. 
Since, the RegistryOffice client is pointing to the current release of application, which is 1.0.0

2022-10-11 16:26 UTC, IswaryaaS commented on RegistryOffice.yaml
> +                                    from [/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-op-s-bm-000/layer-protocol=0/tcp-server-interface-1-0:tcp-server-interface-pac/tcp-serve
The uuid pointing to RO/tcp-server/ipv-4-address need to be updated as ro-2-0-0-tcp-s-bm-000

2022-10-11 16:26 UTC, IswaryaaS commented on RegistryOffice.yaml
> +                                  from [/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-op-s-bm-000/layer-protocol=0/tcp-server-interface-1-0:tcp-server-interface-pac/tcp-server-
The uuid pointing to RO/tcp-server/domain-name need to be updated as ro-2-0-0-tcp-s-bm-000

2022-10-11 16:29 UTC, PrathibaJee approved these changes
Requested review comments are fixed. Many thanks. 
Approving the changes.
Kindly please share your feedback @IswaryaaS . Thanks.

2022-10-11 16:41 UTC, IswaryaaS commented on RegistryOffice.yaml
> +          https://[/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-tcp-c-*/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/r
"/v1/update-client" is called for the callback "ServerReplacementBroadcast", for which the ApiSegment is "im". So, the uuid to be updated as ro-2-0-0-op-c-_im_-\*-1-0-0-001 instead of ro-2-0-0-op-c-_bs_-\*-1-0-0-001

2022-10-11 16:42 UTC, IswaryaaS commented on RegistryOffice.yaml
> +          https://[/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-tcp-c-*/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/r
"/v1/update-operation-client" is called for the callback "OperationUpdateBroadcast", for which the ApiSegment is "im". So, the uuid to be updated as ro-2-0-0-op-c-_im_-\*-1-0-0-002 instead of ro-2-0-0-op-c-_bs_-\*-1-0-0-002

2022-10-11 17:13 UTC, IswaryaaS requested changes
Provided review comments. Kindly resolve.

2022-10-13 07:38 UTC, IswaryaaS commented on RegistryOffice.yaml
> +                    update or create [/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-op-c-is-*-1-0-0-002/layer-protocol=0/operation-client-interface-1-0:operation-client-interfa
The sequence number updated to 004

2022-10-13 07:39 UTC, IswaryaaS commented on RegistryOffice.yaml
> +                    update or create [/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-op-c-*-*-1-0-0-??2/layer-protocol=0/operation-client-interface-1-0:operation-client-interfac
sequence number updated to 004 and updated the uuid

2022-10-13 07:40 UTC, IswaryaaS commented on RegistryOffice.yaml
> +                            from [/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-op-c-*-*-1-0-0-??2/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-pa
sequence number pointing to 004 and updated the uuid

2022-10-13 07:40 UTC, IswaryaaS commented on RegistryOffice.yaml
> +                    update or create [/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-op-c-*-*-1-0-0-001/layer-protocol=0/operation-client-interface-1-0:operation-client-interfac
sequence number updated to 004 and updated the uuid to ro-2-0-0-op-c-im-*-1-0-0-003

2022-10-13 07:41 UTC, IswaryaaS commented on RegistryOffice.yaml
> +                    update or create [/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-op-c-bs-*/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-pac/ope
sequence number updated to 000 and api segment updated to "im"

2022-10-13 07:41 UTC, IswaryaaS commented on RegistryOffice.yaml
> +                    update or create [/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-op-c-bs-*/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-pac/ope
Sequence number updated to 001 and apisegment to "im"

2022-10-13 07:42 UTC, IswaryaaS commented on RegistryOffice.yaml
> +                            from [/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-op-c-is-*-1-0-0-??2/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-p
Sequence number update to 004 and Api segement updated to im

2022-10-13 07:53 UTC, IswaryaaS commented on RegistryOffice.yaml
> +                            from [/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-op-c-*-*-1-0-0-??1/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-pa
sequence number updated to 003 and api segment to im

2022-10-13 07:53 UTC, IswaryaaS commented on RegistryOffice.yaml
> +                            from [/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-op-c-*/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-pac/operation-
Sequence number update to 000 and Api segement updated to im

2022-10-13 07:56 UTC, IswaryaaS commented on RegistryOffice.yaml
> +                            from [/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-op-c-*/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-pac/operation-
Sequence number updated to 001 and Api segement updated to im

2022-10-13 08:04 UTC, IswaryaaS commented on RegistryOffice+services.yaml
> +      uuid: ro-2-0-0-http-c-bm-ro-2-0-0-000
updated the RO client uuid release-number as expected in RO+services.yaml, RO+forwardings.yaml, RO+config.json, RO.yaml

2022-10-13 08:13 UTC, IswaryaaS commented on RegistryOffice.yaml
> +                                  from [/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-op-s-bm-000/layer-protocol=0/tcp-server-interface-1-0:tcp-server-interface-pac/tcp-server-
uuid pointing to registry-office-address is updated to ro-2-0-0-tcp-s-bm-000

2022-10-13 08:13 UTC, IswaryaaS commented on RegistryOffice.yaml
> +                            from [/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-op-s-bm-000/layer-protocol=0/tcp-server-interface-1-0:tcp-server-interface-pac/tcp-server-interf
uuid pointing to registry-office-port is updated to ro-2-0-0-tcp-s-bm-000

2022-10-13 08:16 UTC, IswaryaaS commented on RegistryOffice.yaml
> +          https://[/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-tcp-c-*/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/r
ApiSegment in uuid pointing to /v1/update-client is updated to "im" in https://github.com/openBackhaul/RegistryOffice/pull/152/commits/8ca512402c49b9917b2a5ae3d7ccf157a96ed14c

2022-10-13 08:16 UTC, IswaryaaS commented on RegistryOffice.yaml
> +          https://[/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-tcp-c-*/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/r
ApiSegment in uuid pointing to /v1/update-operation-client is updated to "im" in https://github.com/openBackhaul/RegistryOffice/pull/152/commits/8ca512402c49b9917b2a5ae3d7ccf157a96ed14c

2022-10-13 08:17 UTC, IswaryaaS commented
Review comments have been updated as expected.Thus approving the pull request

2022-10-13 09:12 UTC, openBackhaul approved these changes

2022-10-13 09:13 UTC, merged