Generic representation services to base on Action Profiles #135
openBackhaul/RegistryOffice pull request #166
Opened 2022-10-17 16:54 UTC by vanithavalluripalli9

Fix for Generic representation services to base on Action Profiles
#135

2022-10-18 10:52 UTC, IswaryaaS requested changes
Additionally, I could find "minItems" and "maxItems" constraint in consequent-action-list in various places, which is not required. As per profile instances, we can iterate through the profileInstances for the respective operation-name and form response-body for the available objects [0..*]. If no instance is available for given operation-name, the response-body consequent-action-list will be an empty array []. "So, we can remove the constraints."

2022-10-18 10:52 UTC, IswaryaaS commented on RegistryOffice.yaml
> +                                  from [/core-model-1-4:control-construct/profile-collection/profile=*-2-0-0-action-p-*/action-profile-1-0:action-profile-pac/action-profile-capability/input-value-lis
uuid to be complemented with prefix "ro" instead of *

2022-10-18 10:52 UTC, IswaryaaS commented on RegistryOffice.yaml
> +                            from [/core-model-1-4:control-construct/profile-collection/profile=*-2-0-0-action-p-*/action-profile-1-0:action-profile-pac/action-profile-capability/display-in-new-browse
uuid to be complemented with prefix "ro" instead of *

2022-10-18 11:00 UTC, openBackhaul commented on RegistryOffice.yaml
> +                            from [/core-model-1-4:control-construct/profile-collection/profile=ro-2-0-0-action-p-000/action-profile-1-0:action-profile-pac/action-profile-capability/label or /core-mod
Yes, it would make things much easier during specification, but it has to be understood that ro-2-0-0-action-p-* would have to be filtered for operation-name == "/v1/start-application-in-generic-representation".

2022-10-18 11:00 UTC, openBackhaul commented on RegistryOffice.yaml
> +                            'Request that shall be called, when button gets pressed
see above

2022-10-18 11:03 UTC, openBackhaul commented on RegistryOffice.yaml
> +                                  from [/core-model-1-4:control-construct/profile-collection/profile=*-2-0-0-action-p-*/action-profile-1-0:action-profile-pac/action-profile-capability/input-value-lis
There is no entry in the CONFIGfile for an input-value in that case.
Being unspecific shall indicate this.

The whole description thing for Profile is maybe a little immature.

2022-10-18 11:04 UTC, openBackhaul commented on RegistryOffice.yaml
> +                                  from [/core-model-1-4:control-construct/profile-collection/profile=*-2-0-0-action-p-*/action-profile-1-0:action-profile-pac/action-profile-capability/input-value-lis
see above.

2022-10-18 11:06 UTC, openBackhaul commented on RegistryOffice.yaml
> +                            from [/core-model-1-4:control-construct/profile-collection/profile=*-2-0-0-action-p-*/action-profile-1-0:action-profile-pac/action-profile-capability/label]'
There is no entry in CONFIGfile for label in this case.
Unspecific UUID is indicating this.

2022-10-18 11:06 UTC, openBackhaul commented on RegistryOffice.yaml
> +                            from [/core-model-1-4:control-construct/profile-collection/profile=*-2-0-0-action-p-*/action-profile-1-0:action-profile-pac/action-profile-configuration/request]'
There is no entry in CONFIGfile for request in this case.
Unspecific UUID is indicating this.

2022-10-18 11:06 UTC, openBackhaul commented on RegistryOffice.yaml
> +                                  from [/core-model-1-4:control-construct/profile-collection/profile=*-2-0-0-action-p-*/action-profile-1-0:action-profile-pac/action-profile-capability/input-value-lis
see above

2022-10-18 11:06 UTC, openBackhaul commented on RegistryOffice.yaml
> +                                  from [/core-model-1-4:control-construct/profile-collection/profile=*-2-0-0-action-p-*/action-profile-1-0:action-profile-pac/action-profile-capability/input-value-lis
see above

2022-10-18 11:06 UTC, openBackhaul commented on RegistryOffice.yaml
> +                            from [/core-model-1-4:control-construct/profile-collection/profile=*-2-0-0-action-p-*/action-profile-1-0:action-profile-pac/action-profile-capability/display-in-new-browse
see above

2022-10-20 08:45 UTC, openBackhaul commented on RegistryOffice+profileInstances.yaml
> +  - profile-name: 'ActionProfile'
published OAS = ApplicationPattern OAS + application specific OAS
In regards to the ServiceList, ForwardingList, ProfileList .... etc., I would have planned that the application specific document comprises the basic elements, too.
I will think about removing the basic parts.

2022-10-24 13:12 UTC, openBackhaul commented on RegistryOffice+profileInstances.yaml
> +  - profile-name: 'ActionProfile'
In regards to the ServiceList, ForwardingList, ProfileList .... etc., I would have planned that the application specific document comprises the basic elements, too.

2022-10-24 13:13 UTC, openBackhaul commented on RegistryOffice+profileInstances.yaml
> +  - profile-name: 'ActionProfile'
In regards to the ServiceList, ForwardingList, ProfileList .... etc., I would have planned that the application specific document comprises the basic elements, too.

2022-10-24 13:20 UTC, openBackhaul commented on RegistryOffice.yaml
> +                                  from [/core-model-1-4:control-construct/profile-collection/profile=*-2-0-0-action-p-*/action-profile-1-0:action-profile-pac/action-profile-capability/input-value-lis
Way of describing Profiles changed in several regards.
E.g. entries are now to be described via instances in the CONFIGfile instead of descriptions in OAS.
Also static-field-name and field-name-reference are now two different attributes, which must be used alternatively.

2022-10-24 13:21 UTC, openBackhaul commented on RegistryOffice.yaml
> +                            from [/core-model-1-4:control-construct/profile-collection/profile=*-2-0-0-action-p-*/action-profile-1-0:action-profile-pac/action-profile-capability/label]'
Way of describing Profiles has changed.

2022-10-24 13:22 UTC, openBackhaul commented on RegistryOffice.yaml
> +                            from [/core-model-1-4:control-construct/profile-collection/profile=*-2-0-0-action-p-*/action-profile-1-0:action-profile-pac/action-profile-configuration/request]'
Way of describing Profiles has changed.

2022-10-24 13:22 UTC, openBackhaul commented on RegistryOffice.yaml
> +                                  from [/core-model-1-4:control-construct/profile-collection/profile=*-2-0-0-action-p-*/action-profile-1-0:action-profile-pac/action-profile-capability/input-value-lis
Way of describing Profiles has changed.

2022-10-24 13:22 UTC, openBackhaul commented on RegistryOffice.yaml
> +                                  from [/core-model-1-4:control-construct/profile-collection/profile=*-2-0-0-action-p-*/action-profile-1-0:action-profile-pac/action-profile-capability/input-value-lis
Way of describing Profiles has changed.

2022-10-24 13:22 UTC, openBackhaul commented on RegistryOffice.yaml
> +                            from [/core-model-1-4:control-construct/profile-collection/profile=*-2-0-0-action-p-*/action-profile-1-0:action-profile-pac/action-profile-capability/display-in-new-browse
Way of describing Profiles has changed.

2022-10-24 13:26 UTC, openBackhaul commented on RegistryOffice.yaml
> +                            'Request that shall be called, when button gets pressed
Yes, concept has been changed accordingly.
Descriptions are now generic.
Instances of ActionProfile get listed in the CONFIGfile and have to be filtered by operationName before representing.

2022-10-25 06:39 UTC, IswaryaaS requested changes

2022-10-25 06:39 UTC, IswaryaaS commented on RegistryOffice+services.yaml
>          - service-name: /v1/inform-about-application
A small typo found in line 308 of this file. fake-ip-address of OKM is currently 11.1.3.7. This needs to be corrected as 1.1.3.7.

2022-10-25 16:09 UTC, openBackhaul commented on RegistryOffice+config.json
> +{"ro-2-0-0-op-s-bs-000"
Changed as wished.

2022-10-25 17:11 UTC, openBackhaul commented on RegistryOffice+config.json
> +{"ro-2-0-0-op-s-bs-000"
Changed as wished.

2022-10-25 17:16 UTC, openBackhaul commented on RegistryOffice+config.json
> +                "protocol-reference": "/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-tcp-s-bm-001/layer-protocol=0/tcp-server-interface-1-0:tcp-server-interface-pac/tcp-server-
TcpServer ro-2-0-0-tcp-s-bm-001 added

2022-10-25 17:31 UTC, openBackhaul commented on RegistryOffice+services.yaml
>          - service-name: /v1/inform-about-application
Corrected as indicated. Thanks.

2022-10-26 06:59 UTC, IswaryaaS requested changes

2022-10-26 06:59 UTC, IswaryaaS commented on RegistryOffice+services.yaml
>            uuid: ro-2-0-0-op-s-bs-004
service-name for /docs (ro-2-0-0-op-s-bs-005) needs to be added in services.yaml file. 
Also, please suggest if we can add a definition for /docs as a service in specification (RegistryOffice.yaml) file.

2022-10-26 06:59 UTC, IswaryaaS commented on RegistryOffice+services.yaml
>        individual:
A spelling mistake could be found in line 70 for tcp-server for "tcp" which is given as "tpc".

Also, please suggest if we can add the additional tcp-server instance (ro-2-0-0-tcp-s-bm-001) in RegistryOffice+services.yaml file along with their protocol in respective instances. 

Also, please suggest for adding remote-protocol to tcp-client instances

2022-10-26 06:59 UTC, IswaryaaS commented on RegistryOffice+config.json
> +                "local-protocol": "HTTP",
the required attribute "description" is missing in "tcp-server-interface-configuration" of ro-2-0-0-tcp-s-bm-000 and ro-2-0-0-tcp-s-bm-001. However, this comment can be neglected as it would be added as a part of issue #168

2022-10-26 07:15 UTC, PrathibaJee requested changes

2022-10-26 07:15 UTC, openBackhaul commented on RegistryOffice+services.yaml
>            uuid: ro-2-0-0-op-s-bs-004
service-name: /docs added

2022-10-26 07:18 UTC, openBackhaul commented on RegistryOffice+services.yaml
>            uuid: ro-2-0-0-op-s-bs-004
Would rather not add _/docs:_ path to OAS, because it is automatically created by Swagger.

2022-10-26 07:19 UTC, openBackhaul commented on RegistryOffice+services.yaml
>        individual:
_tpc-server:_ changed into _tcp-server:_.
Thanks for indicating.

2022-10-26 07:23 UTC, openBackhaul commented on RegistryOffice+profileInstances.yaml
> +      protocol-reference: '/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-tcp-s-bm-000/layer-protocol=0/tcp-server-interface-1-0:tcp-server-interface-pac/tcp-server-interface-co
CTRL+H from _tcp-server-interface-configuration/protocol_ to _tcp-server-interface-configuration/local-protocol_. Thanks for indicating.

2022-10-26 07:26 UTC, openBackhaul commented on RegistryOffice+config.json
> +        "uuid": "ro-1-0-0-op-s-bs-005",
Corrected as proposed. Thanks for indicating.

2022-10-26 07:27 UTC, openBackhaul commented on RegistryOffice+config.json
> +        "uuid": "ro-1-0-0-op-s-bs-005",
Corrected as proposed. Thanks for indicating.

2022-10-26 07:28 UTC, openBackhaul commented on RegistryOffice+config.json
> +          "ro-1-0-0-http-s-bm-000"
Corrected as proposed. Thanks for indicating.

2022-10-26 07:28 UTC, openBackhaul commented on RegistryOffice+config.json
> +          "ro-1-0-0-http-s-bm-000"
Corrected as proposed. Thanks for indicating.

2022-10-26 07:37 UTC, openBackhaul commented on RegistryOffice+config.json
> +                "local-protocol": "HTTP",
Done by mistake. Should be HTTPS. Corrected. Thanks for indicating.

2022-10-26 07:42 UTC, openBackhaul commented on RegistryOffice+config.json
> +          "uuid": "ro-2-0-0-response-p-008",
I would prefer creating an additional instance of ResponseProfile for a newly registered application.

2022-10-26 07:45 UTC, openBackhaul commented on RegistryOffice+config.json
> +              "description": "Represents the first entry in the list of releases",
CTRL+H from _"Represents the first entry in the list of releases"_ to _"List of registered application names and release numbers"_. Thanks for indicating.

2022-10-26 07:47 UTC, openBackhaul commented on RegistryOffice+config.json
> +                "field-name-reference": "/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-http-c-okm-ro-1-0-0-000/layer-protocol=0/http-client-interface-1-0:http-client-interface-
Corrected as proposed. Thanks for indicating.

2022-10-26 10:16 UTC, IswaryaaS requested changes

2022-10-27 15:07 UTC, openBackhaul commented on RegistryOffice+services.yaml
> +          uuid: xx-1-0-0-op-s-bs-005
Corrected as requested.

2022-10-27 15:17 UTC, openBackhaul commented on RegistryOffice+services.yaml
>      uuid: ro-2-0-0-tcp-s-bm-000
Added
```
    - description: Without TLS layer
      local-protocol:  http
      own-ip-address:  1.1.3.8
      own-tcp-port: 3008
      uuid: ro-2-0-0-tcp-s-bm-000
    - description: With TLS layer
      local-protocol:  https
      own-ip-address: 1.2.3.8
      own-tcp-port: 3208
      uuid: ro-2-0-0-tcp-s-bm-001
```

2022-10-27 15:24 UTC, openBackhaul commented on RegistryOffice+services.yaml
>      uuid: ro-2-0-0-tcp-s-bm-000
Added 
````
remote-protocol: http
````
at all clients

2022-10-27 15:32 UTC, openBackhaul commented on RegistryOffice+profileInstances.yaml
> +      protocol-reference: '/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-tcp-s-bm-000/layer-protocol=0/tcp-server-interface-1-0:tcp-server-interface-pac/tcp-server-interface-co
Changed all the action-profile references from _ro-2-0-0-tcp-s-bm-000_ to _ro-2-0-0-tcp-s-bm-001_.

2022-10-28 06:10 UTC, IswaryaaS requested changes
Apart from the requested changes in forwardings.yaml file, other changes looks fine

2022-10-28 13:30 UTC, openBackhaul commented on RegistryOffice+forwardings.yaml
>          uuid: ro-2-0-0-op-s-bs-001
Could you please open a separate Issue for documenting your finding.
It is a little remote to the original subject of the pull-request and we need documentation of the changes that need to be made at the other applications, too.
Many thanks for your comments anyway.

2022-10-28 14:31 UTC, merged

2022-10-29 09:31 UTC, IswaryaaS commented on RegistryOffice+forwardings.yaml
>          uuid: ro-2-0-0-op-s-bs-001
documented the issue in https://github.com/openBackhaul/RegistryOffice/issues/180