Remove apiKey from /v1/register-application
openBackhaul/RegistryOffice pull request #188
Opened 2022-11-04 17:50 UTC by openBackhaul

Add InterProfile for wait time to approve

Fixes #10

2022-11-06 13:07 UTC, PrathibaJee requested changes

2022-11-06 13:07 UTC, PrathibaJee commented on RegistryOffice+config.json
> +              "minimum": 60,
Kindly let me know your views in this regards , 

**Assumption :** 
- If a admin configures the value of waitTimeToApprove to 60 seconds. 
- RO application will allow configuration of this value as it is within the acceptable range.

**Consequence :**
- The waitTimeToApprove is 60 seconds , which means within a minute the new application should be approved. 
- For a new registration , practically an approval is not possible within a minute , as it requires a human to approve the request. 
- Can we set the minimum value to 10 minutes (or) to some other values? 

Kindly let me know your views. Thanks.

2022-11-06 13:07 UTC, PrathibaJee commented on RegistryOffice+config.json
>      "logical-termination-point": [
The following comment is not a critical one , mentioning this as we are following a standard across all the services that doesn’t have an apiKeyAuth.

Since we are removing the stereotype security: apiKeyAuth: [] from the /v1/register-application. In the load file , the value of the operation-key shall be changed to "n.a." in the operation-server(ro-2-0-0-op-s-is-001) of this service.
Also , in the operation-client this shall be documented to "n.a.". Thanks.

2022-11-06 13:07 UTC, PrathibaJee commented on RegistryOffice.yaml
>        requestBody:
Since the security option is removed from this service , can we remove the following response code related to unauthorized access from this service.
```
'401':
          $ref: '#/components/responses/responseForErroredServiceRequests'
```
This response code is removed in other services in the ApplicationPattern(inform-about-....) that doesn’t have an apikeyauth.

Also , in the ApplicationPattern , from the callback "PromptForRegisteringCausesRegistrationRequest", this response code shall be removed.

Kindly let me know. Thanks.

2022-11-06 13:07 UTC, PrathibaJee commented on RegistryOffice.yaml
> +  /core-model-1-4:control-construct/profile-collection/profile={uuid}/integer-profile-1-0:integer-profile-pac/integer-profile-capability/integer-name:
Integer profile looks fine and also in the generated server stub its working as expected. Thanks.

2022-11-07 10:06 UTC, openBackhaul commented on RegistryOffice+config.json
> +              "minimum": 60,
Changed as proposed.

2022-11-07 10:12 UTC, openBackhaul commented on RegistryOffice+config.json
>      "logical-termination-point": [
Changed as proposed.

2022-11-07 10:21 UTC, openBackhaul commented on RegistryOffice.yaml
> +  /core-model-1-4:control-construct/profile-collection/profile={uuid}/integer-profile-1-0:integer-profile-pac/integer-profile-capability/integer-name:
Thanks for informing.

2022-11-07 10:32 UTC, openBackhaul commented on RegistryOffice.yaml
>        requestBody:
Checked all services in RegistryOffice and ApplicationPattern, and removed 401 in case of no security option.

2022-11-07 11:22 UTC, PrathibaJee approved these changes
Many thanks for incorporating all the review comments.

2022-11-07 11:25 UTC, merged