Align Callbacks
openBackhaul/RegistryOffice pull request #306
Opened 2022-12-15 17:04 UTC by openBackhaul

Fixes #139

2022-12-16 10:04 UTC, IswaryaaS requested changes
Requesting changes for few findings in which most of the findings are similar.

2022-12-16 15:53 UTC, openBackhaul commented on spec/RegistryOffice.yaml
>                              from [/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-tcp-c-nr-2-0-0-000/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client
CTRL+h from "ro-1-0-0-" to "ro-2-0-0-" in all files.
Changed as proposed.

2022-12-16 15:57 UTC, openBackhaul commented on spec/RegistryOffice.yaml
>                              otherwise protocol for addressing the newly approved application.'
CTRL+h from "tcp-c-*-*-1-0-0" to "tcp-c-*-1-0-0".
Changed as proposed.

2022-12-16 16:02 UTC, openBackhaul commented on spec/RegistryOffice.yaml
> +                release-number:
Changed two occurrences in description of /v1/regard-updated-approval-status::release-number.
Changed as proposed.

2022-12-16 16:10 UTC, openBackhaul commented on spec/RegistryOffice.yaml
> +                        - release-number
Changed as proposed.

2022-12-16 16:12 UTC, openBackhaul commented on spec/RegistryOffice.yaml
> +                        - release-number
Changed as proposed.

2022-12-16 16:17 UTC, openBackhaul commented on spec/RegistryOffice.yaml
>                        type: object
Changed as proposed in both occurrences.

2022-12-16 16:20 UTC, openBackhaul commented on spec/RegistryOffice.yaml
>                        type: object
Changed as proposed in 5 occurrences in total.

2022-12-16 16:28 UTC, openBackhaul commented on spec/RegistryOffice.yaml
>                              from [/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-tcp-c-*/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-
Changed as proposed.

2022-12-16 16:31 UTC, openBackhaul commented on spec/RegistryOffice.yaml
>                              from [/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-op-c-im-*-1-0-0-001/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-p
Changed as proposed.

2022-12-16 16:31 UTC, openBackhaul commented on spec/RegistryOffice.yaml
> +                release-number:
Changed as proposed.

2022-12-16 17:27 UTC, PrathibaJee requested changes

2022-12-16 17:27 UTC, PrathibaJee commented on spec/RegistryOffice+config.json
>            {
In line number 1654  "release-number": "1.0.0" to be changed to "release-number": "2.0.0"

2022-12-16 18:16 UTC, IswaryaaS commented on spec/RegistryOffice+services.yaml
>        release-number: 1.0.0
The corresponding ip-address and port of RegistryOffice client needs to be updated to 1.1.3.8 and 3008

2022-12-16 18:20 UTC, IswaryaaS commented on spec/RegistryOffice+config.json
>            {
once updating the release-number, the corresponding ip-address and port of RegistryOffice client needs to be updated to 1.1.3.8 and 3008

2022-12-16 18:32 UTC, PrathibaJee requested changes

2022-12-16 18:32 UTC, PrathibaJee commented on spec/RegistryOffice.yaml
> +                            from [/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-tcp-c-*-*-*-*-??0/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-
Instead of ro-2-0-0-tcp-c-*-*-*-*-??0 , shall we change it to ro-2-0-0-tcp-c-*-*-*-*-000 ?

2022-12-16 19:21 UTC, PrathibaJee commented
Since this pull request is regarding callbacks , I would like to clarify a small doubt,

For the callback ServerReplacementBroadcast , target entity in the description starts with the **prefix [$** like below , 
```
from [$/v1/relay-server-replacement.body#new-application-port]
```
Where as in OperationUpdateBroadcast , it is in a different format
```
from /v1/relay-operation-update::requestBody::new-operation-name'
```
Kindly let me know is this is for a reason. Thanks.

2022-12-17 09:17 UTC, openBackhaul commented on spec/RegistryOffice+services.yaml
>        release-number: 1.0.0
Changed as proposed.

2022-12-17 09:19 UTC, openBackhaul commented on spec/RegistryOffice+config.json
>            {
Changed as proposed.
Many thanks to both of you.

2022-12-17 09:23 UTC, openBackhaul commented on spec/RegistryOffice.yaml
> +                            from [/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-tcp-c-*-*-*-*-??0/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-
Yes, affected application is no longer coded into these figures.
Changed as proposed.

2022-12-17 09:24 UTC, openBackhaul commented on spec/RegistryOffice.yaml
> +                                    from [/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-tcp-c-*-*-*-*-??0/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp
Yes, affected application is no longer coded into these figures.
Changed as proposed.

2022-12-17 09:24 UTC, openBackhaul commented on spec/RegistryOffice.yaml
> +                                from [/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-tcp-c-*-*-*-*-??0/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-cli
Yes, affected application is no longer coded into these figures.
Changed as proposed.

2022-12-17 09:24 UTC, openBackhaul commented on spec/RegistryOffice.yaml
> +                            from [/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-tcp-c-*-*-*-*-??0/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-
Yes, affected application is no longer coded into these figures.
Changed as proposed.

2022-12-17 10:15 UTC, openBackhaul commented
After receiving the request for broadcasting an update, the RO shall update its internal CONFIG first and sending the broadcast second.
Several descriptions at _/v1/relay-server-replacement_, _/v1/relay-operation-update_ and both callbacks have been changed to be more explicit on the process.
Correct LTPs shall be identified based on equivalence of application name and release number (and operation name) with content of RequestBody.

2022-12-17 13:20 UTC, PrathibaJee requested changes
Thorsten , regarding the changes related to the [comment](https://github.com/openBackhaul/RegistryOffice/pull/306#issuecomment-1356152934) , I have provided my views in the corresponding changed lines. Kindly please let me know your views.

2022-12-17 13:20 UTC, PrathibaJee commented on spec/RegistryOffice.yaml
> +                            from [/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-http-c-*/layer-protocol=0/http-client-interface-1-0:http-client-interface-pac/http-client-interf
The new description is more informative and it will make sure that we are not forwarding a release-number which is not available in RegistryOffice.

2022-12-17 13:20 UTC, PrathibaJee commented on spec/RegistryOffice.yaml
> +                            from [$/v1/relay-operation-update.body#old-operation-name]'
Thanks for changing the format.

2022-12-17 13:20 UTC, PrathibaJee commented on spec/RegistryOffice.yaml
> +                    update [/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-http-c-*/layer-protocol=0/http-client-interface-1-0:http-client-interface-pac/http-client-interface-co
Since the "new-release" related LTPs will already exist in the RO's configuration file, no upgrade is required in the RO.
Also, forwarding "ServerReplacementBroadcast" will have RO's "/v1/update-client" as fc-port output. 
So the RO will also receive the "/v1/update-client" forwarding and update the tcp details if needed and will not update the "release number" because there is already an LTP instance.
Can we change this description back to the previous position? Kindly please let me know your view.

2022-12-17 13:20 UTC, PrathibaJee commented on spec/RegistryOffice.yaml
> +                    update [/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-op-c-*/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-pac/operation-client
In version 1.0.0 implementation, we don't update RO's CONFIGFile with incoming values ​​and use these incoming values ​​directly in "/v1/update-operation-client". Since RO's "/v1/update-operation-client" is part of the fc-port output of OperationUpdateBroadcast, the update of the operation name will happen in that "/v1/update-operation-client" service request. However, there is no harm in updating the values ​​before passing them further.

But kindly let me know shall we change this description back to the previous position? or if you have a different view in this regards. Thanks.

2022-12-18 08:42 UTC, openBackhaul commented on spec/RegistryOffice.yaml
> +                    update [/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-http-c-*/layer-protocol=0/http-client-interface-1-0:http-client-interface-pac/http-client-interface-co
>Since the "new-release" related LTPs will already exist in the RO's configuration file, no upgrade is required in the RO.

Yes, I see your point and will change accordingly.
(Please, regard that attributes' names have changed at AP://v1/update-client and no longer contain "attribute-".)
Equivalence with an existing HttpClient (application name and old release number) is requested for assuring that the broadcast is relating an actually registered application.

>Also, forwarding "ServerReplacementBroadcast" will have RO's "/v1/update-client" as fc-port output.
So the RO will also receive the "/v1/update-client" forwarding and update the tcp details if needed and will not update the "release number" because there is already an LTP instance.

Isn't this a tricky thing?
If RO would update the HttpClient after receiving _RO://v1/update-client_, there would be two HttpClients for the new release and none left for being deleted at the end of the embedding process.
If RO would _not_ update the HttpClient after receiving _RO://v1/update-client_, the OperationClients, which are individual to the updated application, get lost due to deletion at the end of the process.
Doesn't that mean that RO must not sporadically consume some other application's service, but the other application must always create some subscription at RO, which gets individually updated during _/v1/bequeath-your-data-and-die_ by the old release?
Doesn't that apply to all applications, which are creating a stack of clients based on receiving _/v1/regard-application_?

2022-12-18 09:09 UTC, openBackhaul commented on spec/RegistryOffice.yaml
> +                    update [/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-op-c-*/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-pac/operation-client
Having it in synch with all other applications is better.
Broadcast shall pass through the information after verifying existence of the HttpClient.
Changed as proposed.

2022-12-18 15:11 UTC, PrathibaJee commented on spec/RegistryOffice.yaml
> +                    update [/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-http-c-*/layer-protocol=0/http-client-interface-1-0:http-client-interface-pac/http-client-interface-co
>So the RO will also receive the "/v1/update-client" forwarding and update the tcp details if needed and will not update the "release number" because there is already an LTP instance.

My mistake. Initially , the current implementation is not like so. I raised an issue to change the server implementation https://github.com/openBackhaul/ApplicationPattern/issues/464. Also , a small change required in the specification, created an issue https://github.com/openBackhaul/ApplicationPattern/issues/465 , kindly please let me know your views. Thanks.

> If RO would not update the HttpClient after receiving RO://v1/update-client, the OperationClients, which are individual to the updated application, get lost due to deletion at the end of the process.
Doesn't that mean that RO must not sporadically consume some other application's service, but the other application must always create some subscription at RO, which gets individually updated during /v1/bequeath-your-data-and-die by the old release?

Yes , if a **subscription is available** to create operation-client , then during /v1/bequeath-your-data-and-die operation-clients shall be created. This will work fine for most of the same and I see a problem with fewoperation-client of RO in EATL,OL,ALT and OKM, as few of the operation client's dont have a "subscription" available, raised a separate issue https://github.com/openBackhaul/ExecutionAndTraceLog/issues/155

2022-12-18 15:11 UTC, PrathibaJee commented on spec/RegistryOffice.yaml
> +                    update [/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-op-c-*/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-pac/operation-client
Thanks for changing.

2022-12-19 15:53 UTC, IswaryaaS approved these changes

2022-12-19 16:11 UTC, PrathibaJee requested changes
There is one comment that starts with "The /v1/relay-server-replacement service in RO has the following attributes in the requestBody ,......"

Kindly please let me know your views in this comment.
Apart from that others looks fine. Thanks.

2022-12-19 16:11 UTC, PrathibaJee commented on spec/RegistryOffice.yaml
> +                            from [$/v1/relay-server-replacement.body#old-release-number]
The /v1/relay-server-replacement service in RO has the following attributes in the requestBody , 
```
- application-name
- old-application-release-number
- new-application-release-number
- new-application-protocol
- new-application-address
- new-application-port
```

so the description shall be 
from 
from [$/v1/relay-server-replacement.body#old-release-number]
to 
from [$/v1/relay-server-replacement.body#old-application-release-number]

Or 
attributes in the /v1/relay-server-replacement shall be updated.
Kindly let me know your views.

2022-12-19 16:11 UTC, PrathibaJee commented on spec/RegistryOffice.yaml
> +                            from [$/v1/relay-server-replacement.body#old-release-number]
Also , the same comment is applicable for all attributes addressing the $/v1/relay-server-replacement.body#...

2022-12-20 12:39 UTC, openBackhaul commented on spec/RegistryOffice.yaml
> +                    update [/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-http-c-*/layer-protocol=0/http-client-interface-1-0:http-client-interface-pac/http-client-interface-co
I am confirming content of the [AP issue#464 to change the server implementation](https://github.com/openBackhaul/ApplicationPattern/issues/464).
[AP issue#465 for changing the specification](https://github.com/openBackhaul/ApplicationPattern/issues/465) has already been executed.

[EaTL issue#155](https://github.com/openBackhaul/ExecutionAndTraceLog/issues/155) leads to an agreement about transferring OperationClients to HttpClients, in case an HttpClient with new release number does already exist.
Specification has already been changed (description added).

2022-12-20 12:58 UTC, openBackhaul commented on spec/RegistryOffice.yaml
> +                            from [$/v1/relay-server-replacement.body#old-release-number]
Several attributes in the _/v1/relay-server-replacement_ have been shortened by "application-".

2022-12-20 13:23 UTC, PrathibaJee approved these changes
changes to /v1/relay-server-replacement looks fine. Thanks for fixing.

2022-12-20 13:31 UTC, merged