Allow changing application names
openBackhaul/RegistryOffice pull request #312
Opened 2022-12-22 11:55 UTC by openBackhaul

Complement server update broadcast by future application name

Fixes #311

2022-12-22 13:49 UTC, IswaryaaS requested changes

2022-12-22 13:49 UTC, IswaryaaS commented on spec/RegistryOffice.yaml
> +                            from [$/v1/relay-server-replacement.body#future-application-name]'
As per my understanding, the future-application-name and future-release-number should be already present in Config file of RegistryOffice before sending the broadcast to other applications. To make sure that behavior, can we add an description like the one included for current-application-name and current-release-number. (attributes in request body of ServerReplacementBroadcast)
example: 
from [$/v1/relay-server-replacement.body#future-application-name] == [/core-model-1-4:control-construct/logical-termination-point=ro-2-0-0-http-c-*/layer-protocol=0/http-client-interface-1-0:http-client-interface-pac/http-client-interface-configuration/application-name].
I feel if this description is absent, it might be understood that the future-application-name and future-release-number need not require any validation before sending broadcast and can be directly taken from request-body of /v1/relay-server-replacement. 

Kindly let me know your views.

2022-12-22 13:49 UTC, IswaryaaS commented on spec/RegistryOffice.yaml
> +                    and forward to [$/v1/regard-updated-approval-status.callbacks.ServerReplacementBroadcast.body#future-application-name]'
Similar to above comment, can we also add validating path descriptions to future-application-name and future-release-number here as well (In request body of /v1/relay-server-replacement)

2022-12-22 17:59 UTC, openBackhaul commented on spec/RegistryOffice.yaml
> +                            from [$/v1/relay-server-replacement.body#future-application-name]'
Changed as proposed.

2022-12-22 18:02 UTC, openBackhaul commented on spec/RegistryOffice.yaml
> +                    and forward to [$/v1/regard-updated-approval-status.callbacks.ServerReplacementBroadcast.body#future-application-name]'
Changed as proposed.

2022-12-23 03:32 UTC, IswaryaaS requested changes
Requesting changes to very small changes could be found in newly updated descriptions.

2022-12-23 03:32 UTC, IswaryaaS commented on spec/RegistryOffice.yaml
>                              'Name of the application that has updated connection data
description of current-application-name shall be slightly modified to denote "Current application".
LIke 'Name of the application that has updated connection data' to 'Current name of the application that has updated connection data'.

2022-12-23 03:32 UTC, IswaryaaS commented on spec/RegistryOffice.yaml
>                      and forward to [$/v1/regard-updated-approval-status.callbacks.ServerReplacementBroadcast.body#application-name]'
/v1/relay-server-replacement :: current-application-name :: description

"$/v1/regard-updated-approval-status.callbacks.ServerReplacementBroadcast.body#application-name", where the reference attribute "application-name" shall be changed to "$/v1/regard-updated-approval-status.callbacks.ServerReplacementBroadcast.body#**_current-application-name_**"

2022-12-23 03:32 UTC, IswaryaaS commented on spec/RegistryOffice.yaml
>                      and forward to [$/v1/regard-updated-approval-status.callbacks.ServerReplacementBroadcast.body#old-release-number]'
Similarly, /v1/relay-server-replacement :: current-release-number :: description

"$/v1/regard-updated-approval-status.callbacks.ServerReplacementBroadcast.body#old-release-number", where the reference attribute "old-release-number" shall be changed to "$/v1/regard-updated-approval-status.callbacks.ServerReplacementBroadcast.body#**_current-release-number_**"

2022-12-23 03:32 UTC, IswaryaaS commented on spec/RegistryOffice.yaml
>                      forward to [$/v1/regard-updated-approval-status.callbacks.ServerReplacementBroadcast.body#new-release-number]'
Similar to above comments, /v1/relay-server-replacement :: future-release-number, future-protocol, future-address and future-port :: descriptions shall be updated with the word "future" , where we have "new" word as reference

2022-12-23 10:37 UTC, openBackhaul commented on spec/RegistryOffice.yaml
>                              'Name of the application that has updated connection data
Changed as proposed.

2022-12-23 10:44 UTC, openBackhaul commented on spec/RegistryOffice.yaml
>                      and forward to [$/v1/regard-updated-approval-status.callbacks.ServerReplacementBroadcast.body#application-name]'
Changed as proposed.

2022-12-23 10:45 UTC, openBackhaul commented on spec/RegistryOffice.yaml
>                      and forward to [$/v1/regard-updated-approval-status.callbacks.ServerReplacementBroadcast.body#old-release-number]'
Changed as proposed.

2022-12-23 10:46 UTC, openBackhaul commented on spec/RegistryOffice.yaml
>                      forward to [$/v1/regard-updated-approval-status.callbacks.ServerReplacementBroadcast.body#new-release-number]'
Changed as proposed.

2022-12-23 12:42 UTC, IswaryaaS approved these changes

2022-12-23 13:39 UTC, merged