Resolve update the updateApprovalStatusApproved method with protocol value
openBackhaul/RegistryOffice pull request #381
Opened 2023-04-10 12:11 UTC by ManasaBM1

Fixes #380

2023-04-10 12:23 UTC, ManasaBM1 commented
Reviewer is @vanithavalluripalli9

2023-04-10 17:19 UTC, vanithavalluripalli9 requested changes

2023-04-10 17:19 UTC, vanithavalluripalli9 commented on server/service/IndividualServicesService.js
> +        if (applicationAddress === serverAddress || applicationPort === serverPort) {
as address is a object comparing it with "===" will not work . please modify it

2023-04-17 06:26 UTC, vanithavalluripalli9 approved these changes

2023-04-17 06:26 UTC, merged