Resolve while executing the Service if File path does not exist should give Internal Server Error
openBackhaul/RegistryOffice pull request #384
Opened 2023-04-12 05:28 UTC by ManasaBM1

Fixes #376

2023-04-12 05:30 UTC, ManasaBM1 commented
Reviewer is @vanithavalluripalli9

2023-04-17 06:28 UTC, vanithavalluripalli9 requested changes

2023-04-17 06:28 UTC, vanithavalluripalli9 commented on server/service/individualServices/ApplicationPreceedingVersion.js
> +               if(applicationDataFile == undefined){
As discussed , please check whether this change can be included in ApplicationPattern instead of repeating it here everytime

2023-05-23 03:05 UTC, ManasaBM1 commented on server/service/individualServices/ApplicationPreceedingVersion.js
> +               if(applicationDataFile == undefined){
done

2023-05-24 06:51 UTC, vanithavalluripalli9 approved these changes

2023-05-24 06:51 UTC, merged