Implementation to get the waitTimeApprove from integer profile instead of hardcoding the value #373
openBackhaul/RegistryOffice pull request #389
Opened 2023-04-20 08:05 UTC by sunil-kumar-meena

Fixes https://github.com/openBackhaul/RegistryOffice/issues/373

Reviewer is @vanithavalluripalli9

2023-05-10 13:51 UTC, PrathibaJee requested changes

2023-05-10 13:51 UTC, PrathibaJee commented on server/service/individualServices/MonitorTypeApprovalChannel.js
> +                let getMinimumAsync = await IntegerProfile.getMinimumAsync(uuid)
Since the OAM layer takes care of validating the configuration of proper waitTimeToApprove(withing the minimum and maximum value) , this check is additional here. If you feel this is not required, please remove it.

2023-05-10 13:51 UTC, PrathibaJee commented on server/service/individualServices/MonitorTypeApprovalChannel.js
> +                let getMinimumAsync = await IntegerProfile.getMinimumAsync(uuid)
Could you please change the variable names from , 
getMaximumAsync to maximumValue
getMinimumAsync to minimumValue
getOperation to integerValue (or) waitTimeToApprovalValue
Or if you have a better idea, please do so. Thanks.

2023-05-12 05:24 UTC, sunil-kumar-meena commented on server/service/individualServices/MonitorTypeApprovalChannel.js
> +                let getMinimumAsync = await IntegerProfile.getMinimumAsync(uuid)
done

2023-05-12 05:24 UTC, sunil-kumar-meena commented on server/service/individualServices/MonitorTypeApprovalChannel.js
> +                let getMinimumAsync = await IntegerProfile.getMinimumAsync(uuid)
done

2023-05-22 10:23 UTC, PrathibaJee approved these changes
Thanks for resolving the review comments.

2023-05-22 10:23 UTC, merged