Resolve the  isDataTransferRequired check from /v1/bequeath-your-data-and-die implementation as it effects service idempotence concept
openBackhaul/RegistryOffice pull request #436
Opened 2023-06-16 04:38 UTC by ManasaBM1

Fixes #435

2023-06-16 04:38 UTC, ManasaBM1 commented
Reviewer is @PrathibaJee

2023-06-22 15:45 UTC, MartinSunal requested changes

2023-06-22 15:45 UTC, MartinSunal commented on server/service/IndividualServicesService.js
> -          isdataTransferRequired = false;
When this is removed then there is also variable `isdataTransferRequired` on line 84 which is always `true` and it is put to `softwareUpgrade.upgradeSoftwareVersion` on line 137. You should remove `isdataTransferRequired` completely and also from `softwareUpgrade.upgradeSoftwareVersion` signature if it is not used anywhere else.

2023-06-23 09:23 UTC, ManasaBM1 commented on server/service/IndividualServicesService.js
> -          isdataTransferRequired = false;
Done

2023-06-25 19:56 UTC, MartinSunal approved these changes

2023-06-25 19:57 UTC, merged